name: Test Backend and Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-tests:
    name: Test Backend
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
  
      #- name: Run Backend Tests
      #  run: npm test
      #  working-directory: ./backend

  frontend-tests:
    name: Test Frontend with Cypress
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Cypress tests
        working-directory: ./frontend
        run: npm test
